# Server Name Settings
# Here you must put the name of your server, which will be placed in several 
# places within your server automatically
server-name: "&6&lGreekMC"

# Server Info Settins
# Here you must add all the data of your server, this data will be shown in a 
# default message to the players when entering the server
server-storelink: store.greekmc.net
server-twitterlink: "@GreekMC"
server-discordlink: "discord.gg/greekmc"
server-youtubelink: "youtube.com/itoozh"

# Server MOTD Settings
# Server custom MOTD, here we can edit the MOTD of your server and put what you like
server-motd: "&6&lGreek &r&f| &7Lobby"

# Servers for Transfer Settings
# Here you must configure the servers to which the NPC and the Compass will take you, 
# by adding them here you will automatically have them in the Form of the compass and 
# you can also create the NPCs with the command /npc add (server name)
# Use: {n} for \n and {players} for online players in the server
servers.available:
  - name: HCF 
    format: "&6&lHCF&r{n}&7Online: &f{players}"
    address: "199.127.62.88:19060"
  - name: Practice
    format: "§6§lPractice§r{n}&7Online: &f{players}"
    address: "199.127.62.88:19327"
  - name: UHC
    format: "§6§lUHC§r{n}&7Online: &f{players}"
    address: "uhc.greekmc.net:19132"

# ScoreBoard Settings
# Here you can configure the scoreboard, from the title to the lines you want them 
# to have, you can use {players_count}, {player_ping}, {player_nick} to further 
# customize your scoreboard
scoreboard.title: &6&lGreek &r&f| &7Lobby-1
scoreboard.lines:
  - ' &7---------------------'  
  - ' &6Online:' 
  - ' &r&f{players_count}'
  - '&7&r&b'
  - ' &6Nick:'
  - ' &r&f{player_nick}'
  - '&7&r'
  - ' &7greekmc.net'
  - ' &7---------------------&r'


